INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (1, '100', 'E', 'Compra p/ Ind, Prod Rural, Comercialização ou Prest de Serv');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (2, '150', 'E', 'Transf p/ Ind, Prod Rural, Comercialização ou Prest de Serv');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (3, '200', 'E', 'Dev de Venda de Prod Própria, de Terc ou Anulação Valores');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (4, '250', 'E', 'Compra de Energia Elétrica');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (5, '300', 'E', 'Aquisição de Serviço de Comunicação');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (6, '350', 'E', 'Aquisição de Serviço de Transporte');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (7, '400', 'E', 'Entrada de Merc Sujeita ao Regime de Substituição Tributária');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (8, '450', 'E', 'Sistemas de Integração');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (9, '500', 'E', 'Entrada Merc c/ Fim Específico Exportação e Eventual Dev');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (10, '550', 'E', 'Operação c/ Bens Ativo Imobilizado e Mat p/ Uso ou Consumo');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (11, '600', 'E', 'Créditos e Ressarcimentos de ICMS');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (12, '650', 'E', 'Entrada Combustível, Deriv ou Não de Petróleo e Lubrificante');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (13, '900', 'E', 'Outras Entradas de Mercadorias ou Aquisições de Serviços');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (14, '100', 'S', 'Venda de Produção do Estabelecimento');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (15, '150', 'S', 'Transferências de Produção Própria ou de Terceiros');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (16, '200', 'S', 'Dev de Compra p/ Ind, Comercialização ou Anulação Valores');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (17, '250', 'S', 'Venda de Energia Elétrica');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (18, '300', 'S', 'Prestação de Serviço de Comunicação');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (19, '350', 'S', 'Prestação de Serviço de Transporte');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (20, '400', 'S', 'Saída de Merc Sujeita ao Regime de Substituição Tributária');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (21, '450', 'S', 'Sistemas de Integração');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (22, '500', 'S', 'Remessa c/ Fim Específico de Exportação e Eventual Dev');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (23, '500', 'S', 'Exportação de Merc Recebida c/ Fim Específico de Exportação');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (24, '550', 'S', 'Operação c/ Bens Ativo Imobilizado e Mat p/ Uso ou Consumo');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (25, '600', 'S', 'Crédito e Ressarcimento de ICMS');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (26, '650', 'S', 'Saída Combustíveis, Deriv ou Não de Petróleo e Lubrificante');
INSERT INTO tipocfop (id, codigo, entradasaida, descricao) VALUES (27, '900', 'S', 'Outras Saídas de Mercadorias ou Prestações de Serviços');

SELECT setval('tipocfop_id_seq', (SELECT count(id)+2 FROM tipocfop));
