INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1101', 'Compra para industrialização', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1102', 'Compra para comercialização', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1111', 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1113', 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1116', 'Compra para industrialização originada de encomenda para recebimento futuro', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1117', 'Compra para comercialização originada de encomenda para recebimento futuro', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1118', 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1120', 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1121', 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1122', 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1124', 'Industrialização efetuada por outra empresa', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1125', 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1126', 'Compra para utilização na prestação de serviço', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1151', 'Transferência para industrialização', 2);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1152', 'Transferência para comercialização', 2);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1153', 'Transferência de energia elétrica para distribuição', 2);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1154', 'Transferência para utilização na prestação de serviço', 2);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1201', 'Devolução de venda de produção do estabelecimento', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1203', 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1205', 'Anulação de valor relativo à prestação de serviço de comunicação', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1206', 'Anulação de valor relativo à prestação de serviço de transporte', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1207', 'Anulação de valor relativo à venda de energia elétrica', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1208', 'Devolução de produção do estabelecimento, remetida em transferência', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1251', 'Compra de energia elétrica para distribuição ou comercialização', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1252', 'Compra de energia elétrica por estabelecimento industrial', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1253', 'Compra de energia elétrica por estabelecimento comercial', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1254', 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1255', 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1256', 'Compra de energia elétrica por estabelecimento de produtor rural', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1257', 'Compra de energia elétrica para consumo por demanda contratada', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1302', 'Aquisição de serviço de comunicação por estabelecimento industrial', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1303', 'Aquisição de serviço de comunicação por estabelecimento comercial', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1304', 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1305', 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1306', 'Aquisição de serviço de comunicação por estabelecimento de produtor rural', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1352', 'Aquisição de serviço de transporte por estabelecimento industrial', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1353', 'Aquisição de serviço de transporte por estabelecimento comercial', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1360', 'Aquisição de serviço de transporte por contribuinte substituto em relação ao serviço de transporte.', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1401', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1403', 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1406', 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1407', 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1408', 'Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1409', 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1410', 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1411', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1414', 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1415', 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1451', 'Retorno de animal do estabelecimento produtor', 8);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1452', 'Retorno de insumo não utilizado na produção', 8);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1501', 'Entrada de mercadoria recebida com fim específico de exportação', 9);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1503', 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento', 9);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1504', 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros', 9);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1505', 'Entrada decorrente de devolução simbólica de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.', 9);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1506', 'Entrada decorrente de devolução simbólica de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação.', 9);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1551', 'Compra de bem para o ativo imobilizado', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1552', 'Transferência de bem do ativo imobilizado', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1553', 'Devolução de venda de bem do ativo imobilizado', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1554', 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1556', 'Compra de material para uso ou consumo', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1557', 'Transferência de material para uso ou consumo', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1601', 'Recebimento, por transferência, de crédito de ICMS', 11);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1602', 'Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS', 11);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1603', 'Ressarcimento de ICMS retido por substituição tributária', 11);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1604', 'Lançamento do crédito relativo à compra de bem para o ativo imobilizado', 11);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1605', 'Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa.', 11);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1651', 'Compra de combustível ou lubrificante para industrialização subseqüente', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1652', 'Compra de combustível ou lubrificante para comercialização', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1653', 'Compra de combustível ou lubrificante por consumidor ou usuário final', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1658', 'Transferência de combustível e lubrificante para industrialização', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1659', 'Transferência de combustível e lubrificante para comercialização', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1660', 'Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1661', 'Devolução de venda de combustível ou lubrificante destinado à comercialização', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1662', 'Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1663', 'Entrada de combustível ou lubrificante para armazenagem', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1664', 'Retorno de combustível ou lubrificante remetido para armazenagem', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1901', 'Entrada para industrialização por encomenda', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1902', 'Retorno de mercadoria remetida para industrialização por encomenda', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1903', 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1904', 'Retorno de remessa para venda fora do estabelecimento', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1905', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1908', 'Entrada de bem por conta de contrato de comodato', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1909', 'Retorno de bem remetido por conta de contrato de comodato', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1910', 'Entrada de bonificação, doação ou brinde', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1911', 'Entrada de amostra grátis', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1912', 'Entrada de mercadoria ou bem recebido para demonstração', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1913', 'Retorno de mercadoria ou bem remetido para demonstração', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1914', 'Retorno de mercadoria ou bem remetido para exposição ou feira', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1915', 'Entrada de mercadoria ou bem recebido para conserto ou reparo', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1916', 'Retorno de mercadoria ou bem remetido para conserto ou reparo', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1917', 'Entrada de mercadoria recebida em consignação mercantil ou industrial', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1918', 'Devolução de mercadoria remetida em consignação mercantil ou industrial', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1920', 'Entrada de vasilhame ou sacaria', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1921', 'Retorno de vasilhame ou sacaria', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1922', 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1923', 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1924', 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1926', 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1931', 'Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço. (Ajuste SINIEF 03/04)', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1932', 'Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador. (ajuste sinief 03/04)', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1933', 'Aquisição de serviço tributado pelo ISSQN.(ajuste sinief 03/04)', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1949', 'Outra entrada de mercadoria ou prestação de serviço não especificada', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2101', 'Compra para industrialização', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2102', 'Compra para comercialização', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2111', 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2113', 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2116', 'Compra para industrialização originada de encomenda para recebimento futuro', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2117', 'Compra para comercialização originada de encomenda para recebimento futuro', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2118', 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2120', 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2121', 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2122', 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2124', 'Industrialização efetuada por outra empresa', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2125', 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2126', 'Compra para utilização na prestação de serviço', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2151', 'Transferência para industrialização', 2);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2152', 'Transferência para comercialização', 2);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2153', 'Transferência de energia elétrica para distribuição', 2);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2154', 'Transferência para utilização na prestação de serviço', 2);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2201', 'Devolução de venda de produção do estabelecimento', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2203', 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2205', 'Anulação de valor relativo à prestação de serviço de comunicação', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2206', 'Anulação de valor relativo à prestação de serviço de transporte', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2207', 'Anulação de valor relativo à venda de energia elétrica', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2208', 'Devolução de produção do estabelecimento, remetida em transferência', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2251', 'Compra de energia elétrica para distribuição ou comercialização', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2252', 'Compra de energia elétrica por estabelecimento industrial', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2253', 'Compra de energia elétrica por estabelecimento comercial', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2254', 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2255', 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2256', 'Compra de energia elétrica por estabelecimento de produtor rural', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2257', 'Compra de energia elétrica para consumo por demanda contratada', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2302', 'Aquisição de serviço de comunicação por estabelecimento industrial', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2303', 'Aquisição de serviço de comunicação por estabelecimento comercial', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2304', 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2305', 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2306', 'Aquisição de serviço de comunicação por estabelecimento de produtor rural', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2352', 'Aquisição de serviço de transporte por estabelecimento industrial', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2353', 'Aquisição de serviço de transporte por estabelecimento comercial', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2401', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2403', 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2406', 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2407', 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2408', 'Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2409', 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2410', 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2411', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2414', 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2415', 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária', 7);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2501', 'Entrada de mercadoria recebida com fim específico de exportação', 9);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2503', 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento', 9);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2504', 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros', 9);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2505', 'Entrada decorrente de devolução simbólica de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.', 9);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2506', 'Entrada decorrente de devolução simbólica de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação.', 9);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2551', 'Compra de bem para o ativo imobilizado', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2552', 'Transferência de bem do ativo imobilizado', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2553', 'Devolução de venda de bem do ativo imobilizado', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2554', 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2556', 'Compra de material para uso ou consumo', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2557', 'Transferência de material para uso ou consumo', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2603', 'Ressarcimento de ICMS retido por substituição tributária', 11);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2651', 'Compra de combustível ou lubrificante para industrialização subseqüente', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2652', 'Compra de combustível ou lubrificante para comercialização', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2653', 'Compra de combustível ou lubrificante por consumidor ou usuário final', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2658', 'Transferência de combustível e lubrificante para industrialização', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2659', 'Transferência de combustível e lubrificante para comercialização', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2660', 'Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2661', 'Devolução de venda de combustível ou lubrificante destinado à comercialização', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2662', 'Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2663', 'Entrada de combustível ou lubrificante para armazenagem', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2664', 'Retorno de combustível ou lubrificante remetido para armazenagem', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2901', 'Entrada para industrialização por encomenda', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2902', 'Retorno de mercadoria remetida para industrialização por encomenda', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2903', 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2904', 'Retorno de remessa para venda fora do estabelecimento', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2905', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2908', 'Entrada de bem por conta de contrato de comodato', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2909', 'Retorno de bem remetido por conta de contrato de comodato', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2910', 'Entrada de bonificação, doação ou brinde', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2911', 'Entrada de amostra grátis', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2912', 'Entrada de mercadoria ou bem recebido para demonstração', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2913', 'Retorno de mercadoria ou bem remetido para demonstração', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2914', 'Retorno de mercadoria ou bem remetido para exposição ou feira', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2915', 'Entrada de mercadoria ou bem recebido para conserto ou reparo', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2916', 'Retorno de mercadoria ou bem remetido para conserto ou reparo', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2917', 'Entrada de mercadoria recebida em consignação mercantil ou industrial', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2918', 'Devolução de mercadoria remetida em consignação mercantil ou industrial', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2920', 'Entrada de vasilhame ou sacaria', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2921', 'Retorno de vasilhame ou sacaria', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2922', 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2923', 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2924', 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2931', 'Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço. (ajuste sinief 03/04)', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2932', 'Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador. (ajuste sinief 03/04)', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2933', 'Aquisição de serviço tributado pelo ISSQN. (ajuste sinief 03/04)', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2949', 'Outra entrada de mercadoria ou prestação de serviço não especificado', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3101', 'Compra para industrialização', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3102', 'Compra para comercialização', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3126', 'Compra para utilização na prestação de serviço', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3127', 'Compra para industrialização sob o regime de drawback', 1);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3201', 'Devolução de venda de produção do estabelecimento', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3205', 'Anulação de valor relativo à prestação de serviço de comunicação', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3206', 'Anulação de valor relativo à prestação de serviço de transporte', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3207', 'Anulação de valor relativo à venda de energia elétrica', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3211', 'Devolução de venda de produção do estabelecimento sob o regime de drawback', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3217', 'Compra para industrialização sob o regime de "drawback"', 3);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3251', 'Compra de energia elétrica para distribuição ou comercialização', 4);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', 5);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3352', 'Aquisição de serviço de transporte por estabelecimento industrial', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3353', 'Aquisição de serviço de transporte por estabelecimento comercial', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural', 6);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3503', 'Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação', 9);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3551', 'Compra de bem para o ativo imobilizado', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3553', 'Devolução de venda de bem do ativo imobilizado', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3556', 'Compra de material para uso ou consumo', 10);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3651', 'Compra de combustível ou lubrificante para industrialização subseqüente', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3652', 'Compra de combustível ou lubrificante para comercialização', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3653', 'Compra de combustível ou lubrificante por consumidor ou usuário final', 12);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3930', 'Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('3949', 'Outra entrada de mercadoria ou prestação de serviço não especificado', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5101', 'Venda de produção do estabelecimento', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5102', 'Venda de mercadoria adquirida ou recebida de terceiros', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5103', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5105', 'Venda de produção do estabelecimento que não deva por ele transitar', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5109', 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5110', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5111', 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5112', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5113', 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5114', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5115', 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5116', 'Venda de produção do estabelecimento originada de encomenda para entrega futura', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5118', 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5119', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5120', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5122', 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5123', 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5124', 'Industrialização efetuada para outra empresa', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5125', 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5151', 'Transferência de produção do estabelecimento', 15);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5152', 'Transferência de mercadoria adquirida ou recebida de terceiros', 15);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5153', 'Transferência de energia elétrica', 15);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5155', 'Transferência de produção do estabelecimento, que não deva por ele transitar', 15);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5156', 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', 15);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5201', 'Devolução de compra para industrialização', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5202', 'Devolução de compra para comercialização', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5205', 'Anulação de valor relativo a aquisição de serviço de comunicação', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5206', 'Anulação de valor relativo a aquisição de serviço de transporte', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5207', 'Anulação de valor relativo à compra de energia elétrica', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5208', 'Devolução de mercadoria recebida em transferência para industrialização', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5209', 'Devolução de mercadoria recebida em transferência para comercialização', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5210', 'Devolução de compra para utilização na prestação de serviço', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5251', 'Venda de energia elétrica para distribuição ou comercialização', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5252', 'Venda de energia elétrica para estabelecimento industrial', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5253', 'Venda de energia elétrica para estabelecimento comercial', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5254', 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5255', 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5256', 'Venda de energia elétrica para estabelecimento de produtor rural', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5257', 'Venda de energia elétrica para consumo por demanda contratada', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5258', 'Venda de energia elétrica a não contribuinte', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5302', 'Prestação de serviço de comunicação a estabelecimento industrial', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5303', 'Prestação de serviço de comunicação a estabelecimento comercial', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5304', 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5305', 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5306', 'Prestação de serviço de comunicação a estabelecimento de produtor rural', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5307', 'Prestação de serviço de comunicação a não contribuinte', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5351', 'Prestação de serviço de transporte para execução de serviço da mesma natureza', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5352', 'Prestação de serviço de transporte a estabelecimento industrial', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5353', 'Prestação de serviço de transporte a estabelecimento comercial', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5354', 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5355', 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5356', 'Prestação de serviço de transporte a estabelecimento de produtor rural', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5357', 'Prestação de serviço de transporte a não contribuinte', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5359', 'Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal. (ajuste sinief 03/04)', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5360', 'Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte.', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5401', 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5402', 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5403', 'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituto', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5405', 'Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituído', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5408', 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5410', 'Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5411', 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5412', 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5413', 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária.', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5414', 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5415', 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5451', 'Remessa de animal e de insumo para estabelecimento produtor', 21);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5501', 'Remessa de produção do estabelecimento, com fim específico de exportação', 22);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5502', 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação', 22);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5503', 'Devolução de mercadoria recebida com fim específico de exportação', 22);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5504', 'Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.', 22);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5505', 'Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação', 22);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5551', 'Venda de bem do ativo imobilizado', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5552', 'Transferência de bem do ativo imobilizado', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5553', 'Devolução de compra de bem para o ativo imobilizado', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5556', 'Devolução de compra de material de uso ou consumo', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5557', 'Transferência de material de uso ou consumo', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5601', 'Transferência de crédito de ICMS acumulado', 25);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5602', 'Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS', 25);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5603', 'Ressarcimento de ICMS retido por substituição tributária', 25);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5605', 'Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa. (ajuste sinief 03/04)', 25);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5606', 'Utilização de saldo credor de ICMS para extinção por compensação de débitos fiscais.', 25);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5651', 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5652', 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5653', 'Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5654', 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5655', 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5656', 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5657', 'Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5658', 'Transferência de combustível ou lubrificante de produção do estabelecimento', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5659', 'Transferência de combustível ou lubrificante adquirido ou recebido de terceiro', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5660', 'Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5661', 'Devolução de compra de combustível ou lubrificante adquirido para comercialização', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5662', 'Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5663', 'Remessa para armazenagem de combustível ou lubrificante', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5664', 'Retorno de combustível ou lubrificante recebido para armazenagem', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5665', 'Retorno simbólico de combustível ou lubrificante recebido para armazenagem', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5666', 'Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5667', 'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5901', 'Remessa para industrialização por encomenda', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5902', 'Retorno de mercadoria utilizada na industrialização por encomenda', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5903', 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5904', 'Remessa para venda fora do estabelecimento', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5905', 'Remessa para depósito fechado ou armazém geral', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5906', 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5907', 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5908', 'Remessa de bem por conta de contrato de comodato', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5909', 'Retorno de bem recebido por conta de contrato de comodato', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5910', 'Remessa em bonificação, doação ou brinde', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5911', 'Remessa de amostra grátis', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5912', 'Remessa de mercadoria ou bem para demonstração', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5913', 'Retorno de mercadoria ou bem recebido para demonstração', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5914', 'Remessa de mercadoria ou bem para exposição ou feira', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5915', 'Remessa de mercadoria ou bem para conserto ou reparo', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5917', 'Remessa de mercadoria em consignação mercantil ou industrial', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5920', 'Remessa de vasilhame ou sacaria', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5921', 'Devolução de vasilhame ou sacaria', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5924', 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5925', 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5926', 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5927', 'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5928', 'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5931', 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5932', 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5933', 'Prestação de serviço tributado pelo ISSQN. (ajuste sinief 03/04)', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5949', 'Outra saída de mercadoria ou prestação de serviço não especificado', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6101', 'Venda de produção do estabelecimento', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6102', 'Venda de mercadoria adquirida ou recebida de terceiros', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6103', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6105', 'Venda de produção do estabelecimento que não deva por ele transitar', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6107', 'Venda de produção do estabelecimento, destinada a não contribuinte', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6108', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6109', 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6110', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6111', 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6112', 'Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6113', 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6114', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6115', 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6116', 'Venda de produção do estabelecimento originada de encomenda para entrega futura', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6118', 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6119', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6120', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6122', 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6123', 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6124', 'Industrialização efetuada para outra empresa', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6125', 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6151', 'Transferência de produção do estabelecimento', 15);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6152', 'Transferência de mercadoria adquirida ou recebida de terceiros', 15);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6153', 'Transferência de energia elétrica', 15);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6155', 'Transferência de produção do estabelecimento, que não deva por ele transitar', 15);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6156', 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', 15);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6201', 'Devolução de compra para industrialização', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6202', 'Devolução de compra para comercialização', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6205', 'Anulação de valor relativo a aquisição de serviço de comunicação', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6206', 'Anulação de valor relativo a aquisição de serviço de transporte', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6207', 'Anulação de valor relativo à compra de energia elétrica', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6208', 'Devolução de mercadoria recebida em transferência para industrialização', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6209', 'Devolução de mercadoria recebida em transferência para comercialização', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6210', 'Devolução de compra para utilização na prestação de serviço', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6251', 'Venda de energia elétrica para distribuição ou comercialização', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6252', 'Venda de energia elétrica para estabelecimento industrial', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6253', 'Venda de energia elétrica para estabelecimento comercial', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6254', 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6255', 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6256', 'Venda de energia elétrica para estabelecimento de produtor rural', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6257', 'Venda de energia elétrica para consumo por demanda contratada', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6258', 'Venda de energia elétrica a não contribuinte', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6302', 'Prestação de serviço de comunicação a estabelecimento industrial', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6303', 'Prestação de serviço de comunicação a estabelecimento comercial', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6304', 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6305', 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6306', 'Prestação de serviço de comunicação a estabelecimento de produtor rural', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6307', 'Prestação de serviço de comunicação a não contribuinte', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6351', 'Prestação de serviço de transporte para execução de serviço da mesma natureza', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6352', 'Prestação de serviço de transporte a estabelecimento industrial', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6353', 'Prestação de serviço de transporte a estabelecimento comercial', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6354', 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6355', 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6356', 'Prestação de serviço de transporte a estabelecimento de produtor rural', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6357', 'Prestação de serviço de transporte a não contribuinte', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6359', 'Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal. (ajuste sinief 03/04)', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6360', 'Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6401', 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6402', 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6403', 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6404', 'Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6408', 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6410', 'Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6411', 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6412', 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6413', 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6414', 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6415', 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária', 20);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6501', 'Remessa de produção do estabelecimento, com fim específico de exportação', 22);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6502', 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação', 22);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6503', 'Devolução de mercadoria recebida com fim específico de exportação', 22);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6504', 'Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.', 22);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6505', 'Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação', 22);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6551', 'Venda de bem do ativo imobilizado', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6552', 'Transferência de bem do ativo imobilizado', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6553', 'Devolução de compra de bem para o ativo imobilizado', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6556', 'Devolução de compra de material de uso ou consumo', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6557', 'Transferência de material de uso ou consumo', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6603', 'Ressarcimento de ICMS retido por substituição tributária', 25);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6651', 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6652', 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6653', 'Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6654', 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6655', 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6656', 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6657', 'Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6658', 'Transferência de combustível ou lubrificante de produção do estabelecimento', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6659', 'Transferência de combustível ou lubrificante adquirido ou recebido de terceiro', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6660', 'Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6661', 'Devolução de compra de combustível ou lubrificante adquirido para comercialização', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6662', 'Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6663', 'Remessa para armazenagem de combustível ou lubrificante', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6664', 'Retorno de combustível ou lubrificante recebido para armazenagem', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6665', 'Retorno simbólico de combustível ou lubrificante recebido para armazenagem', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6666', 'Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6667', 'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação diferente a da que ocorrer o consumo', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6901', 'Remessa para industrialização por encomenda', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6902', 'Retorno de mercadoria utilizada na industrialização por encomenda', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6903', 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6904', 'Remessa para venda fora do estabelecimento', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6905', 'Remessa para depósito fechado ou armazém geral', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6906', 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6907', 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6908', 'Remessa de bem por conta de contrato de comodato', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6909', 'Retorno de bem recebido por conta de contrato de comodato', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6910', 'Remessa em bonificação, doação ou brinde', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6911', 'Remessa de amostra grátis', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6912', 'Remessa de mercadoria ou bem para demonstração', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6913', 'Retorno de mercadoria ou bem recebido para demonstração', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6914', 'Remessa de mercadoria ou bem para exposição ou feira', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6915', 'Remessa de mercadoria ou bem para conserto ou reparo', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6917', 'Remessa de mercadoria em consignação mercantil ou industrial', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6920', 'Remessa de vasilhame ou sacaria', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6921', 'Devolução de vasilhame ou sacaria', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6924', 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6925', 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6931', 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6932', 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6933', 'Prestação de serviço tributado pelo ISSQN (ajuste sinief 03/04)', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6949', 'Outra saída de mercadoria ou prestação de serviço não especificado', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7101', 'Venda de produção do estabelecimento', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7102', 'Venda de mercadoria adquirida ou recebida de terceiros', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7105', 'Venda de produção do estabelecimento, que não deva por ele transitar', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7127', 'Venda de produção do estabelecimento sob o regime de drawback', 14);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7201', 'Devolução de compra para industrialização', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7202', 'Devolução de compra para comercialização', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7205', 'Anulação de valor relativo à aquisição de serviço de comunicação', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7206', 'Anulação de valor relativo a aquisição de serviço de transporte', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7207', 'Anulação de valor relativo à compra de energia elétrica', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7210', 'Devolução de compra para utilização na prestação de serviço', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7211', 'Devolução de compras para industrialização sob o regime de drawback', 16);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7251', 'Venda de energia elétrica para o exterior', 17);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', 18);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7358', 'Prestação de serviço de transporte', 19);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7501', 'Exportação de mercadorias recebidas com fim específico de exportação', 23);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7551', 'Venda de bem do ativo imobilizado', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7553', 'Devolução de compra de bem para o ativo imobilizado', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7556', 'Devolução de compra de material de uso ou consumo', 24);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7651', 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7654', 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7667', 'Venda de combustível ou lubrificante a consumidor ou usuário final', 26);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7930', 'Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('7949', 'Outra saída de mercadoria ou prestação de serviço não especificado', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('1934', 'Entrada simbólica de mercadoria recebida para depósito fechado ou armazém-geral', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('2934', 'Entrada simbólica de mercadoria recebida para depósito fechado ou armazém-geral', 13);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5923', 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém-geral ou depósito fechado', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6923', 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém-geral ou depósito fechado', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('5934', 'Remessa simbólica de mercadoria depositada em armazém-geral ou depósito fechado', 27);
INSERT INTO cfop (codigo, descricao, tipocfop_id) VALUES ('6934', 'Remessa simbólica de mercadoria depositada em armazém-geral ou depósito fechado', 27);

SELECT setval('cfop_id_seq', (SELECT count(id)+2 FROM cfop));
