INSERT INTO pais (id, nome) VALUES (132, 'Afeganistão');
INSERT INTO pais (id, nome) VALUES (175, 'Albânia, República da');
INSERT INTO pais (id, nome) VALUES (230, 'Alemanha');
INSERT INTO pais (id, nome) VALUES (310, 'Burkina Faso');
INSERT INTO pais (id, nome) VALUES (370, 'Andorra');
INSERT INTO pais (id, nome) VALUES (400, 'Angola');
INSERT INTO pais (id, nome) VALUES (418, 'Anguilla');
INSERT INTO pais (id, nome) VALUES (434, 'Antígua e Barbuda');
INSERT INTO pais (id, nome) VALUES (477, 'Antilhas Holandesas');
INSERT INTO pais (id, nome) VALUES (531, 'Arábia Saudita');
INSERT INTO pais (id, nome) VALUES (590, 'Argélia');
INSERT INTO pais (id, nome) VALUES (639, 'Argentina');
INSERT INTO pais (id, nome) VALUES (647, 'Armênia, República da');
INSERT INTO pais (id, nome) VALUES (655, 'Aruba');
INSERT INTO pais (id, nome) VALUES (698, 'Austrália');
INSERT INTO pais (id, nome) VALUES (728, 'Áustria');
INSERT INTO pais (id, nome) VALUES (736, 'Azerbaijão, República do');
INSERT INTO pais (id, nome) VALUES (779, 'Bahamas, Ilhas');
INSERT INTO pais (id, nome) VALUES (809, 'Bahrein, Ilhas');
INSERT INTO pais (id, nome) VALUES (817, 'Bangladesh');
INSERT INTO pais (id, nome) VALUES (833, 'Barbados');
INSERT INTO pais (id, nome) VALUES (850, 'Belarus, República da');
INSERT INTO pais (id, nome) VALUES (876, 'Bélgica');
INSERT INTO pais (id, nome) VALUES (884, 'Belize');
INSERT INTO pais (id, nome) VALUES (906, 'Bermudas');
INSERT INTO pais (id, nome) VALUES (930, 'Mianmar (Birmânia)');
INSERT INTO pais (id, nome) VALUES (973, 'Bolívia');
INSERT INTO pais (id, nome) VALUES (981, 'Bosnia-Herzegovina (República da)');
INSERT INTO pais (id, nome) VALUES (1015, 'Botsuana');
INSERT INTO pais (id, nome) VALUES (1058, 'Brasil');
INSERT INTO pais (id, nome) VALUES (1082, 'Brunei');
INSERT INTO pais (id, nome) VALUES (1112, 'Bulgária, República da');
INSERT INTO pais (id, nome) VALUES (1155, 'Burundi');
INSERT INTO pais (id, nome) VALUES (1198, 'Butão');
INSERT INTO pais (id, nome) VALUES (1279, 'Cabo Verde, República de');
INSERT INTO pais (id, nome) VALUES (1376, 'Cayman, Ilhas');
INSERT INTO pais (id, nome) VALUES (1414, 'Camboja');
INSERT INTO pais (id, nome) VALUES (1457, 'Camarões');
INSERT INTO pais (id, nome) VALUES (1490, 'Canadá');
INSERT INTO pais (id, nome) VALUES (1504, 'Guernsey, Ilha do Canal (Inclui Alderney e Sark)');
INSERT INTO pais (id, nome) VALUES (1508, 'Jersey, Ilha do Canal');
INSERT INTO pais (id, nome) VALUES (1511, 'Canárias, Ilhas');
INSERT INTO pais (id, nome) VALUES (1538, 'Cazaquistão, República do');
INSERT INTO pais (id, nome) VALUES (1546, 'Catar');
INSERT INTO pais (id, nome) VALUES (1589, 'Chile');
INSERT INTO pais (id, nome) VALUES (1600, 'China, República Popular');
INSERT INTO pais (id, nome) VALUES (1619, 'Formosa (Taiwan)');
INSERT INTO pais (id, nome) VALUES (1635, 'Chipre');
INSERT INTO pais (id, nome) VALUES (1651, 'Cocos (Keeling), Ilhas');
INSERT INTO pais (id, nome) VALUES (1694, 'Colômbia');
INSERT INTO pais (id, nome) VALUES (1732, 'Comores, Ilhas');
INSERT INTO pais (id, nome) VALUES (1775, 'Congo');
INSERT INTO pais (id, nome) VALUES (1830, 'Cook, Ilhas');
INSERT INTO pais (id, nome) VALUES (1872, 'Coréia, Rep. Pop. Democrática');
INSERT INTO pais (id, nome) VALUES (1902, 'Coréia, República da');
INSERT INTO pais (id, nome) VALUES (1937, 'Costa do Marfim');
INSERT INTO pais (id, nome) VALUES (1953, 'Croácia (República da)');
INSERT INTO pais (id, nome) VALUES (1961, 'Costa Rica');
INSERT INTO pais (id, nome) VALUES (1988, 'Coveite');
INSERT INTO pais (id, nome) VALUES (1996, 'Cuba');
INSERT INTO pais (id, nome) VALUES (2291, 'Benin');
INSERT INTO pais (id, nome) VALUES (2321, 'Dinamarca');
INSERT INTO pais (id, nome) VALUES (2356, 'Dominica, Ilha');
INSERT INTO pais (id, nome) VALUES (2399, 'Equador');
INSERT INTO pais (id, nome) VALUES (2402, 'Egito');
INSERT INTO pais (id, nome) VALUES (2437, 'Eritreia');
INSERT INTO pais (id, nome) VALUES (2445, 'Emirados Árabes Unidos');
INSERT INTO pais (id, nome) VALUES (2453, 'Espanha');
INSERT INTO pais (id, nome) VALUES (2461, 'Eslovênia, República da');
INSERT INTO pais (id, nome) VALUES (2470, 'Eslovaca, República');
INSERT INTO pais (id, nome) VALUES (2496, 'Estados Unidos');
INSERT INTO pais (id, nome) VALUES (2518, 'Estônia, República da');
INSERT INTO pais (id, nome) VALUES (2534, 'Etiópia');
INSERT INTO pais (id, nome) VALUES (2550, 'Falkland (Ilhas Malvinas)');
INSERT INTO pais (id, nome) VALUES (2593, 'Feroe, Ilhas');
INSERT INTO pais (id, nome) VALUES (2674, 'Filipinas');
INSERT INTO pais (id, nome) VALUES (2712, 'Finlândia');
INSERT INTO pais (id, nome) VALUES (2755, 'Franca');
INSERT INTO pais (id, nome) VALUES (2810, 'Gabão');
INSERT INTO pais (id, nome) VALUES (2852, 'Gâmbia');
INSERT INTO pais (id, nome) VALUES (2895, 'Gana');
INSERT INTO pais (id, nome) VALUES (2917, 'Geórgia, República da');
INSERT INTO pais (id, nome) VALUES (2933, 'Gibraltar');
INSERT INTO pais (id, nome) VALUES (2976, 'Granada');
INSERT INTO pais (id, nome) VALUES (3018, 'Grécia');
INSERT INTO pais (id, nome) VALUES (3050, 'Groenlândia');
INSERT INTO pais (id, nome) VALUES (3093, 'Guadalupe');
INSERT INTO pais (id, nome) VALUES (3131, 'Guam');
INSERT INTO pais (id, nome) VALUES (3174, 'Guatemala');
INSERT INTO pais (id, nome) VALUES (3255, 'Guiana Francesa');
INSERT INTO pais (id, nome) VALUES (3298, 'Guine');
INSERT INTO pais (id, nome) VALUES (3310, 'Guiné-Equatorial');
INSERT INTO pais (id, nome) VALUES (3344, 'Guiné-Bissau');
INSERT INTO pais (id, nome) VALUES (3379, 'Guiana');
INSERT INTO pais (id, nome) VALUES (3417, 'Haiti');
INSERT INTO pais (id, nome) VALUES (3450, 'Honduras');
INSERT INTO pais (id, nome) VALUES (3514, 'Hong Kong');
INSERT INTO pais (id, nome) VALUES (3557, 'Hungria, República da');
INSERT INTO pais (id, nome) VALUES (3573, 'Iêmen');
INSERT INTO pais (id, nome) VALUES (3595, 'Man, Ilha de');
INSERT INTO pais (id, nome) VALUES (3611, 'Índia');
INSERT INTO pais (id, nome) VALUES (3654, 'Indonésia');
INSERT INTO pais (id, nome) VALUES (3697, 'Iraque');
INSERT INTO pais (id, nome) VALUES (3727, 'Ira, República Islâmica do');
INSERT INTO pais (id, nome) VALUES (3751, 'Irlanda');
INSERT INTO pais (id, nome) VALUES (3794, 'Islândia');
INSERT INTO pais (id, nome) VALUES (3832, 'Israel');
INSERT INTO pais (id, nome) VALUES (3867, 'Itália');
INSERT INTO pais (id, nome) VALUES (3913, 'Jamaica');
INSERT INTO pais (id, nome) VALUES (3964, 'Johnston, Ilhas');
INSERT INTO pais (id, nome) VALUES (3999, 'Japão');
INSERT INTO pais (id, nome) VALUES (4030, 'Jordânia');
INSERT INTO pais (id, nome) VALUES (4111, 'Kiribati');
INSERT INTO pais (id, nome) VALUES (4200, 'Laos, Rep. Pop. Democr. do');
INSERT INTO pais (id, nome) VALUES (4260, 'Lesoto');
INSERT INTO pais (id, nome) VALUES (4278, 'Letônia, República da');
INSERT INTO pais (id, nome) VALUES (4316, 'Líbano');
INSERT INTO pais (id, nome) VALUES (4340, 'Libéria');
INSERT INTO pais (id, nome) VALUES (4383, 'Líbia');
INSERT INTO pais (id, nome) VALUES (4405, 'Liechtenstein');
INSERT INTO pais (id, nome) VALUES (4421, 'Lituânia, República da');
INSERT INTO pais (id, nome) VALUES (4456, 'Luxemburgo');
INSERT INTO pais (id, nome) VALUES (4472, 'Macau');
INSERT INTO pais (id, nome) VALUES (4499, 'Macedônia, Ant. Rep. Iugoslava');
INSERT INTO pais (id, nome) VALUES (4502, 'Madagascar');
INSERT INTO pais (id, nome) VALUES (4525, 'Madeira, Ilha da');
INSERT INTO pais (id, nome) VALUES (4553, 'Malásia');
INSERT INTO pais (id, nome) VALUES (4588, 'Malavi');
INSERT INTO pais (id, nome) VALUES (4618, 'Maldivas');
INSERT INTO pais (id, nome) VALUES (4642, 'Mali');
INSERT INTO pais (id, nome) VALUES (4677, 'Malta');
INSERT INTO pais (id, nome) VALUES (4723, 'Marianas do Norte');
INSERT INTO pais (id, nome) VALUES (4740, 'Marrocos');
INSERT INTO pais (id, nome) VALUES (4766, 'Marshall, Ilhas');
INSERT INTO pais (id, nome) VALUES (4774, 'Martinica');
INSERT INTO pais (id, nome) VALUES (4855, 'Mauricio');
INSERT INTO pais (id, nome) VALUES (4880, 'Mauritânia');
INSERT INTO pais (id, nome) VALUES (4901, 'Midway, Ilhas');
INSERT INTO pais (id, nome) VALUES (4936, 'México');
INSERT INTO pais (id, nome) VALUES (4944, 'Moldávia, República da');
INSERT INTO pais (id, nome) VALUES (4952, 'Mônaco');
INSERT INTO pais (id, nome) VALUES (4979, 'Mongólia');
INSERT INTO pais (id, nome) VALUES (4985, 'Montenegro');
INSERT INTO pais (id, nome) VALUES (4995, 'Micronésia');
INSERT INTO pais (id, nome) VALUES (5010, 'Montserrat, Ilhas');
INSERT INTO pais (id, nome) VALUES (5053, 'Moçambique');
INSERT INTO pais (id, nome) VALUES (5070, 'Namíbia');
INSERT INTO pais (id, nome) VALUES (5088, 'Nauru');
INSERT INTO pais (id, nome) VALUES (5118, 'Christmas, Ilha (Navidad)');
INSERT INTO pais (id, nome) VALUES (5177, 'Nepal');
INSERT INTO pais (id, nome) VALUES (5215, 'Nicarágua');
INSERT INTO pais (id, nome) VALUES (5258, 'Niger');
INSERT INTO pais (id, nome) VALUES (5282, 'Nigéria');
INSERT INTO pais (id, nome) VALUES (5312, 'Niue, Ilha');
INSERT INTO pais (id, nome) VALUES (5355, 'Norfolk, Ilha');
INSERT INTO pais (id, nome) VALUES (5380, 'Noruega');
INSERT INTO pais (id, nome) VALUES (5428, 'Nova Caledônia');
INSERT INTO pais (id, nome) VALUES (5452, 'Papua Nova Guiné');
INSERT INTO pais (id, nome) VALUES (5487, 'Nova Zelândia');
INSERT INTO pais (id, nome) VALUES (5517, 'Vanuatu');
INSERT INTO pais (id, nome) VALUES (5568, 'Oma');
INSERT INTO pais (id, nome) VALUES (5665, 'Pacífico, Ilhas do (Possessão dos EUA)');
INSERT INTO pais (id, nome) VALUES (5738, 'Países Baixos (Holanda)');
INSERT INTO pais (id, nome) VALUES (5754, 'Palau');
INSERT INTO pais (id, nome) VALUES (5762, 'Paquistão');
INSERT INTO pais (id, nome) VALUES (5800, 'Panamá');
INSERT INTO pais (id, nome) VALUES (5860, 'Paraguai');
INSERT INTO pais (id, nome) VALUES (5894, 'Peru');
INSERT INTO pais (id, nome) VALUES (5932, 'Pitcairn, Ilha');
INSERT INTO pais (id, nome) VALUES (5991, 'Polinésia Francesa');
INSERT INTO pais (id, nome) VALUES (6033, 'Polônia, República da');
INSERT INTO pais (id, nome) VALUES (6076, 'Portugal');
INSERT INTO pais (id, nome) VALUES (6114, 'Porto Rico');
INSERT INTO pais (id, nome) VALUES (6238, 'Quênia');
INSERT INTO pais (id, nome) VALUES (6254, 'Quirguiz, República');
INSERT INTO pais (id, nome) VALUES (6289, 'Reino Unido');
INSERT INTO pais (id, nome) VALUES (6408, 'República Centro-Africana');
INSERT INTO pais (id, nome) VALUES (6475, 'República Dominicana');
INSERT INTO pais (id, nome) VALUES (6602, 'Reunião, Ilha');
INSERT INTO pais (id, nome) VALUES (6653, 'Zimbábue');
INSERT INTO pais (id, nome) VALUES (6700, 'Romênia');
INSERT INTO pais (id, nome) VALUES (6750, 'Ruanda');
INSERT INTO pais (id, nome) VALUES (6769, 'Rússia, Federação da');
INSERT INTO pais (id, nome) VALUES (6777, 'Salomão, Ilhas');
INSERT INTO pais (id, nome) VALUES (6781, 'Saint Kitts e Nevis');
INSERT INTO pais (id, nome) VALUES (6858, 'Saara Ocidental');
INSERT INTO pais (id, nome) VALUES (6874, 'El Salvador');
INSERT INTO pais (id, nome) VALUES (6904, 'Samoa');
INSERT INTO pais (id, nome) VALUES (6912, 'Samoa Americana');
INSERT INTO pais (id, nome) VALUES (6955, 'São Cristóvão e Neves, Ilhas');
INSERT INTO pais (id, nome) VALUES (6971, 'San Marino');
INSERT INTO pais (id, nome) VALUES (7005, 'São Pedro e Miquelon');
INSERT INTO pais (id, nome) VALUES (7056, 'São Vicente e Granadinas');
INSERT INTO pais (id, nome) VALUES (7102, 'Santa Helena');
INSERT INTO pais (id, nome) VALUES (7153, 'Santa Lucia');
INSERT INTO pais (id, nome) VALUES (7200, 'São Tome e Príncipe, Ilhas');
INSERT INTO pais (id, nome) VALUES (7285, 'Senegal');
INSERT INTO pais (id, nome) VALUES (7315, 'Seychelles');
INSERT INTO pais (id, nome) VALUES (7358, 'Serra Leoa');
INSERT INTO pais (id, nome) VALUES (7370, 'Servia');
INSERT INTO pais (id, nome) VALUES (7412, 'Cingapura');
INSERT INTO pais (id, nome) VALUES (7447, 'Síria, República Árabe da');
INSERT INTO pais (id, nome) VALUES (7480, 'Somália');
INSERT INTO pais (id, nome) VALUES (7501, 'Sri Lanka');
INSERT INTO pais (id, nome) VALUES (7544, 'Suazilândia');
INSERT INTO pais (id, nome) VALUES (7560, 'África do Sul');
INSERT INTO pais (id, nome) VALUES (7595, 'Sudão');
INSERT INTO pais (id, nome) VALUES (7641, 'Suécia');
INSERT INTO pais (id, nome) VALUES (7676, 'Suíça');
INSERT INTO pais (id, nome) VALUES (7706, 'Suriname');
INSERT INTO pais (id, nome) VALUES (7722, 'Tadjiquistão, República do');
INSERT INTO pais (id, nome) VALUES (7765, 'Tailândia');
INSERT INTO pais (id, nome) VALUES (7803, 'Tanzânia, Rep. Unida da');
INSERT INTO pais (id, nome) VALUES (7820, 'Território Brit. Oc. Índico');
INSERT INTO pais (id, nome) VALUES (7838, 'Djibuti');
INSERT INTO pais (id, nome) VALUES (7889, 'Chade');
INSERT INTO pais (id, nome) VALUES (7919, 'Tcheca, República');
INSERT INTO pais (id, nome) VALUES (7951, 'Timor Leste');
INSERT INTO pais (id, nome) VALUES (8001, 'Togo');
INSERT INTO pais (id, nome) VALUES (8052, 'Toquelau, Ilhas');
INSERT INTO pais (id, nome) VALUES (8109, 'Tonga');
INSERT INTO pais (id, nome) VALUES (8150, 'Trinidad e Tobago');
INSERT INTO pais (id, nome) VALUES (8206, 'Tunísia');
INSERT INTO pais (id, nome) VALUES (8230, 'Turcas e Caicos, Ilhas');
INSERT INTO pais (id, nome) VALUES (8249, 'Turcomenistão, República do');
INSERT INTO pais (id, nome) VALUES (8273, 'Turquia');
INSERT INTO pais (id, nome) VALUES (8281, 'Tuvalu');
INSERT INTO pais (id, nome) VALUES (8311, 'Ucrânia');
INSERT INTO pais (id, nome) VALUES (8338, 'Uganda');
INSERT INTO pais (id, nome) VALUES (8451, 'Uruguai');
INSERT INTO pais (id, nome) VALUES (8478, 'Uzbequistão, República do');
INSERT INTO pais (id, nome) VALUES (8486, 'Vaticano, Est. da Cidade do');
INSERT INTO pais (id, nome) VALUES (8508, 'Venezuela');
INSERT INTO pais (id, nome) VALUES (8583, 'Vietnã');
INSERT INTO pais (id, nome) VALUES (8630, 'Virgens, Ilhas (Britânicas)');
INSERT INTO pais (id, nome) VALUES (8664, 'Virgens, Ilhas (EUA.)');
INSERT INTO pais (id, nome) VALUES (8702, 'Fiji');
INSERT INTO pais (id, nome) VALUES (8737, 'Wake, Ilha');
INSERT INTO pais (id, nome) VALUES (8885, 'Congo, República Democrática do');
INSERT INTO pais (id, nome) VALUES (8907, 'Zâmbia');
INSERT INTO pais (id, nome) VALUES (8958, 'Zona do Canal do Panamá');
INSERT INTO pais (id, nome) VALUES (9999, 'Exterior');
