INSERT INTO estado (id, sigla, nome, pais_id) VALUES (17, 'TO', 'Tocantins', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (11, 'RO', 'Rondônia', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (12, 'AC', 'Acre', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (13, 'AM', 'Amazonas', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (14, 'RR', 'Roraima', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (15, 'PA', 'Pará', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (16, 'AP', 'Amapá', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (21, 'MA', 'Maranhão', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (22, 'PI', 'Piauí', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (23, 'CE', 'Ceará', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (24, 'RN', 'Rio Grande do Norte', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (25, 'PB', 'Paraíba', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (27, 'AL', 'Alagoas', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (28, 'SE', 'Sergipe', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (29, 'BA', 'Bahia', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (26, 'PE', 'Pernambuco', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (31, 'MG', 'Minas Gerais', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (32, 'ES', 'Espírito Santo', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (33, 'RJ', 'Rio de Janeiro', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (35, 'SP', 'São Paulo', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (41, 'PR', 'Paraná', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (42, 'SC', 'Santa Catarina', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (43, 'RS', 'Rio Grande do Sul', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (50, 'MS', 'Mato Grosso do Sul', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (51, 'MT', 'Mato Grosso', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (52, 'GO', 'Goiás', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (53, 'DF', 'Distrito Federal', 1058);
INSERT INTO estado (id, sigla, nome, pais_id) VALUES (99, 'EX', 'Exterior', 9999);

SELECT setval('estado_id_seq', (SELECT count(id)+2 FROM estado));
