CREATE OR REPLACE FUNCTION public.atualizaestoqueaposentradadeproduto() RETURNS trigger
    LANGUAGE plpgsql
    AS $body$
BEGIN
	IF NEW.TIPOMOVIMENTO = 'E' THEN
UPDATE PRODUTO SET QUANTIDADEMINIMA = QUANTIDADEMINIMA + NEW.QUANTIDADE WHERE ID = NEW.PRODUTO_ID;

END IF;
RETURN NEW;
END;
$body$;