default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  username: postgres # Utilizado para acessar o banco (opção -U)
  password: root
  port: 5433
  pool: 75

development:
  <<: *default
  host: copel.gtech.site
  database: business_raul
  username: postgres 
  password: g2010tech
  port: 5433

test:
  <<: *default
  host: 127.0.0.1
  database: businessmanager_test
  username: postgres
  password: g2010tech
  port: 5433

fiscal_development:
  <<: *default
  host: copel.gtech.site
  user: postgres
  username: postgres # Utilizado para acessar o banco (opção -U)
  database: fiscal_raul
  password: g2010tech
  pool: 25
  port: 5433

api_development:
  <<: *default
#  database: api-dev
  database: api_raul
  host: copel.gtech.site
  user: postgres
  username: postgres
  password: g2010tech
  pool: 25
  port: 5433
